### ISSUE TITLE
Handling of CRLF and LF - RFC 2822 STRICT or BEST PRACTISE

### ISSUE THREAD

**Issue by TomFreudenberg** [4commerce-technologies-AG/midi-smtp-server#16]
**Describe the current situation**

There is a difference between the conformity of [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) and _best practise_.

In RFC 2822 it says that strictly each line has to end up by CR (code 13) followed by LF (code 10). And in addition that the chars CR (code 13) and LF (code 10) should not be used particulary. If looking on Qmails implementation, they will revoke any traffic which is not conform to the above per default.

In the real world, it is established, that also a line ending with single LF (code 10) is good practise. So if trying other mailservers like Exim or Exchange or Gmail, you may enter your message either ended by CRLF or single LF.

Also the DATA ending sequence of CRLF.CRLF (CR LF DOT CR LF) may be send as LF.LF (LF DOT LF).

<br>

**Expected behavior**

From my personal point of view, I would _like to have all systems working conform to the RFCs_ but during that is not the reality, I like (mostly) compatible systems.

For that my expected behavior is, that MidiSmtpServer will accept CRLF as well as LF only.

But if possible we should try to make the world a bit better and should _repair_ the non conform messages like:

1. Read input buffer and search for LF (code 10)
2. Use bytes from buffer start to LF as _TEXTLINE_
3. Delete any occurence of char CR (code 13) and char LF (code 10) from _TEXTLINE_
4. Append cleaned _TEXTLINE_ and RFC conform pair of CRLF to message data buffer

In result we will have a clean RFC 2822 conform message input data.

In best it is 100% equal to the original input because it already was RFC conform.

For others the content (line breaks) maybe have changed but the message is processable.

<br>

**System (please complete the following information):**
 - MidiSmtpServer version [>=2.3.0]

<br>

**Describe the question**

With version 2.3.0 we have changed the processing of entered lines to handle them like described in _Expected behavior_.

The question is now, may you (users of MidiSmtpServer) confirm that:

a. this is best practise and the component should stay with that per default

or

b. need to add an option to allow a setting like `strict` or `best_practise` mode?

<br>

**Additional information**

Here you find the commit https://github.com/4commerce-technologies-AG/midi-smtp-server/commit/f1250762dbfb477266db344e3051935089f69a62

**Comment by TomFreudenberg** [comment]
Hey guys @gencer, @mwhobrey, @kaspergrubbe

may I ask you once more to check this question an leave your personal feedback.

Thanks for your help
Tom

**Comment by gencer** [comment]
Hi @TomFreudenberg,

When there is two option available, I always go with second option.

> b. need to add an option to allow a setting like strict or best_practise mode?

This will be better with if we can choose between `strict` mode or `best_practise`. Instead of making decision for clients ourselves, let's leave this setting to users who want to deal with.

This is my personal opinion. Of course you have the last word.

**Comment by olemd** [comment]
My two cent goes to _compatible_ as default, but _strict_ as a configurable option.

**Comment by gencer** [comment]
@TomFreudenberg, Definitely *compatible* should be default.

**Comment by TomFreudenberg** [comment]
Ok, thanks for your feedback and opinions. That helps to decide.

It will be update like that:

``` ruby
  # default values for conformity to RFC(2)822 and addtionals
  # if interested in details, checkout discussion on issue queue at:
  # https://github.com/4commerce-technologies-AG/midi-smtp-server/issues/16
  CRLF_MODES = [:CRLF_ENSURE, :CRLF_LEAVE, :CRLF_STRICT]
  DEFAULT_CRLF_MODE = :CRLF_ENSURE
```

**Text from README.md**

## RFC(2)822 - Handle CRLF and LF

There is a difference between the conformity of RFC 2822 and best practise.

In [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) it says that strictly each line has to end up by CR (code 13) followed by LF (code 10). And in addition that the chars CR (code 13) and LF (code 10) should not be used particulary. If looking on Qmails implementation, they will revoke any traffic which is not conform to the above per default.

In real world, it is established, that also a line ending with single LF (code 10) is good practise. So if trying other mailservers like Exim or Exchange or Gmail, you may enter your message either ended by CRLF or single LF.

Also the DATA ending sequence of CRLF.CRLF (CR LF DOT CR LF) may be send as LF.LF (LF DOT LF).

Since version 2.3.0 the component allows to decide by option `crlf_mode` how to handle the line termination codes. Be aware that `CRLF_ENSURE` is enabled by default.

```ruby
# Allow CRLF and LF but always make sure that CRLF is added to message data. _Default_
opts = { crlf_mode: CRLF_ENSURE }

# Allow CRLF and LF and do not change the incoming data.
opts = { crlf_mode: CRLF_LEAVE }

# Only allow CRLF otherwise raise an exception
opts = { crlf_mode: CRLF_STRICT }
```

To understand the modes in details:

#### CRLF_ENSURE

1. Read input buffer and search for LF (code 10)
2. Use bytes from buffer start to LF as TEXTLINE
3. Heal by deleting any occurence of char CR (code 13) and char LF (code 10) from TEXTLINE
4. Append cleaned TEXTLINE and RFC conform pair of CRLF to message data buffer

* As result you will have a clean RFC 2822 conform message input data
* In best case the data is 100% equal to the original input because that already was CRLF conform
* Other input data maybe have changed for the linebreaks but the message is conform yet

#### CRLF_LEAVE

1. Read input buffer and search for LF (code 10)
2. Use bytes from buffer start to LF as TEXTLINE
3. Append TEXTLINE as is to message data buffer

* As result you may have a non clean RFC 2822 conform message input data
* Other libraries like `Mail` may have parsing errors

#### CRLF_STRICT

1. Read input buffer and search for CRLF (code 13 code 10)
2. Use bytes from buffer start to CRLF as TEXTLINE
3. Raise exception if TEXTLINE contains any single CR or LF
3. Append TEXTLINE as is to message data buffer

* As result you will have a clean RFC 2822 conform message input data
* The data is 100% equal to the original input because that already was CRLF conform
* You maybe drop mails while in real world not all senders are working RFC conform

**Comment by TomFreudenberg** [comment]
Implemented and tested - see commit https://github.com/4commerce-technologies-AG/midi-smtp-server/commit/8317af81070479871d10492770aa2bd5fa7e7e74

**Comment by TomFreudenberg** [comment]
Hi all, thanks for participating.

Cheers
Tom

**Comment by gencer** [comment]
@TomFreudenberg, You are awesome! Thank you!
