### ISSUE TITLE
Celluloid::IO based midi-smtp-server clone.

### ISSUE THREAD

**Issue by digitalextremist** [4commerce-technologies-AG/midi-smtp-server#2]
https://github.com/abstractive/celluloid-smtp

Very new code, curious to hear feedback as to whether it'd be better to change to a `Celluloid::IO` server in general. Any benchmark comparisons would be welcome also.

**Comment by TomFreudenberg** [comment]
Hi thanks for linking and using the parser from here. I have not yet checked or benchmarked but looked at your implementation. Maybe you like to also re-use the new AUTH mechanism (not yet finished - CRAM is missing)

**Comment by digitalextremist** [comment]
Thanks, I will check out the `AUTH` implementation and see about porting that.

**Comment by TomFreudenberg** [comment]
@digitalextremist Hi

STARTTLS is now also finished nearly ... maybe interesting as well.
