### ISSUE TITLE
Potential / trivial bug to instantiate service twice on same IP address

### ISSUE THREAD

**Issue by TomFreudenberg** [4commerce-technologies-AG/midi-smtp-server#26]
While working on PR for mailcatcher the issue / enhancement #25 was seen. That also opens the potential for wrong initialization of SMTP server instances.

if e.g. using 'localhost' and '127.0.01' for host name pattern, MidiSmtpServer will try to instiate twice on same address.

**Expected behavior**

To prevent that, the given hosts (ips and names) should been resolved to their ip address and then instatiated on the ip addresses.

**Comment by TomFreudenberg** [comment]
I am just before launching release 3 of midi-smtp-server.

**This will not be _"magically"_ resolved!**

Reason: As many tests and thoughts I did during the last updates, I came to the conclusion that it is very important that the _administrator_ of a running service is aware on the ip-addresses and ports the midi-smtp-server components are listening on.

So doing some magically fixes on wrong defined parameters will not help to make the world better :-) So for that, my highly suggested proposal is to define ip-addresses as ipv4 and ipv6 adresses and not use loose _namings_ to bind services on.

If your server will handle ipv4 and ipv6 network, the "localhost" parameter will bind on **both** adapters. If you have to define only one or **have to be sure** that both are available, better user "127.0.0.1, ::1" as parameter.

This is not a bug anymore but wished feature. If you define somewhere same ip-addresses in the end, midi-smtp-server will raise exception like "cannot bind to address:port - already in use"

Cheers
Tom

**Comment by gencer** [comment]
Hey @TomFreudenberg! It's good to see you back on this!

For the reply; I see. Thanks for the clarification.
