### ISSUE TITLE
Catch up exceptions in def serve_service_on_ip_address_and_port()

### ISSUE THREAD

**Issue by TomFreudenberg** [4commerce-technologies-AG/midi-smtp-server#29]
By looking the source code, I see that you catch the exceptions (`rescue`) and if its not handled (`StandardError`) you fallback with `logger.fatal(e.backtrace.join("\n"))`. In this case im not able to catch the exceptions myself so that i can log to 3rd party applications like Sentry.

What is the best way to handle exception catching without breaking default procedure?

Here: https://github.com/4commerce-technologies-AG/midi-smtp-server/blob/6ac3636fa9fd36d78c736378b13808295e6d5b1b/lib/midi-smtp-server.rb#L521

For example, lets say i have a module and method like this:

```ruby

def check_user
  user = unknown_method # raise here but it seems MidiSmtpServer already catch this.
rescue StandardError => e
  Sentry.capture_exception e # <- this never gets called
end
```

**Comment by TomFreudenberg** [comment]
Hi @gencer, I moved your question to a seperate issue.

I guess you are looking just at a not usable position.

To be honest - those errors should under normal conditions never ever reached or raised.

Just to make it sure that your code will never break - however a client may close or drop or down or whatever do with the TCP Connection.

Your case seems to be more "in a session"?

Could you please define a bit more what you want to get?

**Comment by gencer** [comment]
Thanks for this @TomFreudenberg! Sorry for not being create an issue at first place!

One way would be to provide our own lambdas:

```ruby
daemon = MySmtpd.new(ports: '2525', hosts: '127.0.0.1', max_processings: 4, on_error: ->(e) {
   Sentry.capture_exception e
})
```

Hook name can be `on_error`, `after_error` or similar... So you can call this lambda after everything is done by MidiSmtpServer.

**Comment by gencer** [comment]
> Hi @gencer, I moved your question to a seperate issue.
> 
> I guess you are looking just at a not usable position.
> 
> To be honest - those errors should under normal conditions never ever reached or raised.
> 
> Just to make it sure that your code will never break - however a client may close or drop or down or whatever do with the TCP Connection.
> 
> Your case seems to be more "in a session"?
> 
> Could you please define a bit more what you want to get?

Lets say an exception raised inside of SMTPServer but this exception is system specific. We handle raises here beautifully. So that server never gets down. However, somehow we need this exception report being reported to our system so we can look the root cause.

Currently it silences and only logs to log file or logger.

I would like to carch all remaining `StandardError`'s and report them into Sentry.

**Comment by gencer** [comment]
> > Currently it silences and only logs to log file or logger.
> > I would like to catch all remaining StandardError's and report them into Sentry.
> 
> Ah, I see - you want to change the logger - I will check that

Actually, I do use custom logger. It logs to MongoDB Server. However, logs are not reports. I cannot know if exception raises or not without looking to logs manually. What i want to do is to catch those exceptions and report to Sentry as-is. Loggers also modify backtrace's a bit which causes to not be able to find root case.

At my first reply, a hook (lambda function) may work here. So you catche the Close errors and others then log to log and call this lambda so we can get the report

**Comment by TomFreudenberg** [comment]
In any case @gencer - I will add also the error message to the fatal log what is not done curently

change lines:

```ruby
logger.fatal(e.backtrace.join("\n"))
```

into: 

```ruby
logger.fatal(e.backtrace.insert(0, "#{e}").join("\n"))
```

**Comment by gencer** [comment]
But just a side now. Your sample only report "message". I will not be able to get Line numbers, backtrace etc...

**Comment by TomFreudenberg** [comment]
Hi @gencer

> Believe me, this didn't come up to my mind. I should sleep more I guess :) I've been awake since 2 days.

That does mean - append your own logger is suitable for you?

> But just a side now. Your sample only report "message". I will not be able to get Line numbers, backtrace etc...

When reporting via `logger.fatal` the backtrace is included in the complete `message` block.

When reporting a `logger.error` _only_ its only the message.

Does that fit also?

**Comment by TomFreudenberg** [comment]
Hmm ... looking again and again on the code :-)

logger.error() occurs inside sessions only

```ruby
              # defined SmtpdException
              rescue SmtpdException => e
                # inc number of detected exceptions during this session
                session[:ctx][:server][:exceptions] += 1
                # log error info if logging
                logger.error("#{e}")
                # get the given smtp dialog result
                output = +"#{e.smtpd_result}"

              # Unknown general Exception during processing
              rescue StandardError => e
                # inc number of detected exceptions during this session
                session[:ctx][:server][:exceptions] += 1
                # log error info if logging
                logger.error("#{e}")
                # set default smtp server dialog error
                output = +"#{Smtpd500Exception.new.smtpd_result}"
              end
```

I already send a _info_ to the context with

```ruby
  session[:ctx][:server][:exceptions] += 1
```

I guess adding the exceptions here as a list would be an improvement too:

```ruby
  session[:ctx][:server][:exceptions].push({ message: "#{e}", backtrace: e.backtrace.dup })
```

So you can also inspect the exceptions during the session runs inside the running thread

**Comment by TomFreudenberg** [comment]
Hi @gencer

You now can access a new session property 

```ruby
# array containing the fully cloned occured error objects
ctx[:server][:errors].each { |e| puts e.inspect }
```

just as a note, those values are identically but I won't break the API - so decided for seperate property `errors`

```ruby
puts ctx[:server][:errors].length == ctx[:server][:exceptions]
```

**Comment by TomFreudenberg** [comment]
NP - I am also extending the logging currently - still wait for next commit

**Comment by TomFreudenberg** [comment]
Hey @gencer 

I guess I am ready now ...

You find a NEW EVENT now on the class which you may override for your needs

```ruby
def on_logging_event(_ctx, severity, msg, err: nil)
```

Internally I have created a forwarding logger class bound to logger property. So in any case some will use `logger.xyz(msg)` inside code, that message is routed to the new `on_logging_event`. In that case, while using `logger.xyz()` the context `ctx` and `err` object is nil.

All internal logger output are rewritten to the new event. That enables you now to catch any error and exception object by just overriding this event:

```ruby
def on_logging_event(_ctx, severity, msg, err: nil)
  send_to_sentry(err) if err
  super
end
```

Thats easy - isnt it?

If you wish to extend you own loggings inside your application you also may use the event method like:

```ruby
def on_helo_event(ctx, helo_data)
  # do something
  
  # new log with context and / or err
  on_logging_event(ctx, Logger::WARN, "My Warning", err: nil)

  # just as simple as ever
  logger.warn("My Warning")
```

All will be send forward the new event to catch what you like.

As for this change I marked the property `logger` in `Smtpd.new` as deprecated. Whoever wants to change the logger output should use the new event from now on.

Good luck and I am looking forward to your response.

P.S.: Thanks for that idea and extending the component

P.P.S.: I will write some new tests for that in addition

**Comment by TomFreudenberg** [comment]
Just to make it sure that both enhancements from today make sense:

1. ctx[:server][:errors]

With this new attached array of occurred and catched errors you may modify the session workflow when detecting errors. This enables to update the sessions behavior to your needs.

2. on_logging_event()

With this new event you may catch with the backbone any logger message and push that to something like sentry or database etc. This is just to update the backend logging to your needs.

**Comment by gencer** [comment]
Hey @TomFreudenberg,

Tested on my end and this is more than I expect. Now i can do more with the exceptions and loggings. I just fired an exception and Sentry got it:

![image](https://user-images.githubusercontent.com/1711576/110689867-46842200-81f4-11eb-8c1d-5c4e2a08347d.png)


```ruby
  def on_logging_event(ctx, severity, msg, err: nil)
    Sentry.capture_exception(err) if err
    # And even, do some scoping, tagging etc... As we have separate instance of logger
    # we can now attach indsividual email data (like which user/ email) to the logging context or
    # sentry context.
    SemanticLogger['Distributer'].error msg if severity >= 1
    super
  end
```

**Comment by TomFreudenberg** [comment]
Hi @gencer - so we may close this issue here as resolved?

**Comment by gencer** [comment]
Yes, sure we can! Resolved thanks to you!

**Comment by TomFreudenberg** [comment]
Hi @gencer - off topic question:

Do you like to show me or tell me something about your solution for what you are using MidiSmtpServer?

I am very interested in hearing about that - sound as it it a cool service

**Comment by TomFreudenberg** [comment]
P.S. @gencer you may send me a private mail at: 

th DOT freudenberg AT gmail DOT com

**Comment by gencer** [comment]
Hey @TomFreudenberg,

Tomorrow you'll get the email. I do not want to just send 3 lines of email. I am going to send you overview of what MidiSmtpServer does on our system, what happens in the background and how I extended it (-and with). Also some screenshots from Frontend.

I am going to reinstall my Windows due to I *** up the system and awesomely deleted the backup images just before I do that, so cannot return to previous state ! Wonderful isn't it :)

Gencer.

**Comment by TomFreudenberg** [comment]
I was wondering if the new logging will slow down the services significant and so I wrote a benchmark for that.

Test should identifiy:

1. Best for speed is calling logger.debug directly
2. when using new on_logging_event will this slow down logger process
3. when using forwarder.call will this slow down the logger process

Benchmark

```ruby
require 'benchmark/ips'
require 'logger'

N = 100_000

LOGGER = Logger.new('/tmp/log.bench.txt')

class Forwarder
  def initialize(on_log)
    @on_log = on_log
  end

  def debug(msg)
    @on_log.call(Logger::DEBUG, msg)
  end
end

class Master
  attr_reader :forward

  def initialize
    @forward = Forwarder.new(method(:on_log))
  end

  def on_log(severity, msg)
    case severity
      when Logger::DEBUG
        LOGGER.debug(msg)
    end
  end
end

master = Master.new

Benchmark.ips do |x|

  x.report('logger direct') do
    N.times do
      LOGGER.debug('A simple message A')
    end
  end

  x.report('master on event') do
    N.times do
      master.on_log(Logger::DEBUG, 'A simple message B')
    end
  end

  x.report('master forward') do
    N.times do
      master.forward.debug('A simple message C')
    end
  end

  x.compare!
end

puts ""
puts ""
```

The RESULT shows - **using event or call WON'T slow down significant**

<pre>
Warming up --------------------------------------
       logger direct     1.000  i/100ms
     master on event     1.000  i/100ms
      master forward     1.000  i/100ms

Calculating -------------------------------------
       logger direct      0.948  (± 0.0%) i/s -      5.000  in   5.273358s
     master on event      0.821  (± 0.0%) i/s -      5.000  in   6.107497s
      master forward      0.788  (± 0.0%) i/s -      4.000  in   5.120721s

Comparison:
       logger direct:        0.9 i/s
     master on event:        0.8 i/s - 1.15x  (± 0.00) slower
      master forward:        0.8 i/s - 1.20x  (± 0.00) slower
</pre>

<br>

New logging feature is also speed tested !!!
