### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by chrise86** [4commerce-technologies-AG/midi-smtp-server#3]
How would I go about passing authentication using this? I intend on using it inside a Rails app, but currently passing the smtp standard `user_name` and `password` gives:

`>>> 500 Syntax error, command unrecognised or error in parameters or arguments`

**Comment by TomFreudenberg** [comment]
Hi @chrise86 

I am sorry but currently this component does not provide AUTH mechanism like described at e.g. http://www.samlogic.net/articles/smtp-commands-reference-auth.htm

I have checked that but it seems to need a one day to implement that feature. Do you in a hurry with that? I could try to spent some free time within the next month on it.

If you like, I also will have a look on a PR you may send me.

Thanks for short feedback
Tom

**Comment by chrise86** [comment]
That's great thanks @TomFreudenberg. I'll look in to it in the mean time, but if you can look at it too that would be great! :)

**Comment by TomFreudenberg** [comment]
Do you need encrypted authentification (usage via internet) or just plain authentification (inhouse / serval internal connections)?

**Comment by chrise86** [comment]
Um, I guess encrypted, for client applications

**Comment by TomFreudenberg** [comment]
Ok, so it is the full package ;-)

**Comment by yms9654** [comment]
+1

**Comment by yms9654** [comment]
I made a pull request for this.
https://github.com/4commerce-technologies-AG/midi-smtp-server/pull/4

**Comment by TomFreudenberg** [comment]
Hi, after the PR from @yms9654  #4 

I started to define the interface for authentification today. This is what it will look like:

````
# check the authentification
def on_auth_event(ctx, username, password_or_hash)
end
````

An additional property is usable during session like

````
authentificated?
````

Two `opts` setting to the daemon like

````
# enable the SMTPD authentification dialog
# if disabled, only anonymous usage is possible
opts = { enable_auth: true }

# if anonymous is allowed, server does not
# automatically reject un-authorized connections
opts = { allow_anonymous: true }
````

This is something I still have to think about:

````
# be aware of deadlock (tbd)
# enable_auth = false and allow_anonymous = false
# will block all connections
````

The implementation can decide wether and how to use authentification or not.

Cheers
Tom

**Comment by TomFreudenberg** [comment]
Hi, for all interested, I made a first push tonight and implemented PLAIN and LOGIN mechanism like described in RFCs.

You need to implement your own user / access rules via new `on_auth_event` located at

https://github.com/4commerce-technologies-AG/midi-smtp-server/blob/master/lib/midi-smtp-server.rb#L135-L143

You have to enable authentification during initialization like

````
server = MySmtpd.new(MidiSmtpServer::DEFAULT_SMTPD_PORT, MidiSmtpServer::DEFAULT_SMTPD_HOST, MidiSmtpServer::DEFAULT_SMTPD_MAX_CONNECTIONS, { auth_mode: :AUTH_REQUIRED }) 
````

If you want to deny access, you have to call the `super` method or `raise Smtpd535Exception`. If you want to pass the authetication, you may return the value of the user which is then stored in your `ctx` as `authorization_id`.

For the moment check `ctx[:server]` values after authentication.

I will update README soon and go on with implementing CRAM-MD5

Cheers
Tom

**Comment by TomFreudenberg** [comment]
@chrise86 @yms9654 

I updated the README.md and described how to use AUTH within your app. I have not yet packaged the new gem for that, because I like you to test this changes if possible.

It should work now for `AUTH LOGIN` and `AUTH PLAIN` in any cases. 

I will add support for `EHLO` and `CRAM-MD5` soon.

Thanks for your comments
Tom

**Comment by TomFreudenberg** [comment]
@chrise86 @yms9654 

I read a lot about securing transport on SMTP by now and after all I prefer to use SMTPS instead of implementing CRAM-MD5 for password challenge only.

This means, that for authorization there are those two options `AUTH LOGIN` and `AUTH PLAIN`. You can decide then if you want to run the service on PORT 25 as unencrypted or on PORT 465 as encrypted service.

A numerous number of mail providers had already decided to drop CRAM-MD5 and let people switch over to complete encrypted communication.

What do you think about this decision?

Thanks for your comments
Tom

**Comment by TomFreudenberg** [comment]
I published the new version on RubyGems at https://rubygems.org/gems/midi-smtp-server/versions/2.1.0

**Comment by TomFreudenberg** [comment]
Hi @chrise86 @yms9654 

I will close this issue as solved by now and create another enhancement about SMTPS. Thanks for supporting.

Tom

**Comment by yms9654** [comment]
Thank you, @TomFreudenberg!
:+1:
