### ISSUE TITLE
Feature: load chain PEM file and optionally include the KEY as well

### ISSUE THREAD

**Issue by TomFreudenberg** [4commerce-technologies-AG/midi-smtp-server#36]
With PR #33 @ocha has enabled the load of a CHAIN PEM file.

When reading [DigiCert PEM creation](https://www.digicert.com/kb/ssl-support/pem-ssl-creation.htm) you will find also some information that the key file maybe already included in the chain.

This should be get handled here as well.

Last but not least from Ruby/OpenSSL there is also a PR about reading a CHAIN PEM file at https://github.com/ruby/openssl/pull/441

Checkout how to use this once it is deployed.

**Comment by TomFreudenberg** [comment]
Checkout also this revert commit: 

https://github.com/ruby/openssl/commit/23b07043e7fde743ff920f8354b5a094fee19a03

**Comment by TomFreudenberg** [comment]
Checkout this answer to create a chained test PEM

https://superuser.com/a/1556884

**Comment by TomFreudenberg** [comment]
**TODO**

change "soft" deprecated properties

```ruby 
        @ssl_context.cert = certs.first
        @ssl_context.extra_chain_cert = certs[1..]
        @ssl_context.key = OpenSSL::PKey::RSA.new(File.open(@key_path.to_s))
```

to 

```ruby
        #@ssl_context.add_certificate(@ssl_context.cert, @ssl_context.key, @ssl_context.extra_chain_cert)
```

The problem on this is currently - no access to the added certs anymore.

**Comment by TomFreudenberg** [comment]
@ocha

Hi Luri,

I appended also the option to include the key in the PEM file

and wrote some tests for the chained PEM files.

Could you please also run some tests if that fits.

I will prepare a new release after your feedback.

Cheers
Tom

**Comment by TomFreudenberg** [comment]
@ocha

You do not need to write additional tests - I just ask you to test this master branch with your current setup - if all is fine

**Comment by TomFreudenberg** [comment]
Hey @gencer 

I am just a moment before publishing a new release. (3.0.2)

It would be nice if you have the option to run the latest master branch once on your side and put me some feedback. I do not expect any issues 😉 

Best wishes and hope you are well
Tom

**Comment by gencer** [comment]
@TomFreudenberg Thanks for the heads up. I'll test and report back to you with my application.

**Comment by ocha** [comment]
Hey @TomFreudenberg. 

I just tested latest master branch with my setup and everything works as expected. I did not test explicitly embedding private key into the PEM file. I did test cert chain and validation from smtp client. 

Thanks!

**Comment by gencer** [comment]
@TomFreudenberg Sorry for my late reply. At my first test, I got errors on client-side then on server-side. However, all of them caused by certificate chains. (My mistake) 

Currently, on `master` branch I am able to receive all messages as usual on `production` environment. I've already deployed `master` branch on all prod machines.

No issues so far. It just works™.

**Comment by TomFreudenberg** [comment]
Hey guys,

thanks for your feedback - so the new release will be pushed.

Closing this
