### ISSUE TITLE
How to use/configure to send a real email

### ISSUE THREAD

**Issue by petervandeput** [4commerce-technologies-AG/midi-smtp-server#43]
**Describe the question**
Want to use it as the email sender so need to configure for example on mydomain.com and allow me to send emails from info@mydomain.com to any email address in the world.
this requires DNS lookup and forwarding. Is this not supported or am i missing something

**Expected behavior**

**System (please complete the following information):**
 - OS: [e.g. OSX 10.13]
 - Ruby: [e.g. 2.5.1 (rvm.io)]
 - MidiSmtpServer version [e.g. 2.2.4]

**Additional information**
Add any other information about your question here.

**Comment by TomFreudenberg** [comment]
Hi Peter,

this component is for getting emails from clients like Outlook or Exchange or whatever sender is used.

You are the able to do whatever you like to do with the mail - also can forward your mails anywhere to the outside. For that you would use an additional client component like Mikel mail.

Please have a look at the Slack reciepe server:

https://github.com/4commerce-technologies-AG/midi-smtp-server/blob/master/cookbook/recipe-slack/src/service/midi-smtp-server-recipe-slack-mta.rb

there you will find code to read for interpreting incoming mails and forwarding them via slack interface (https).

If you look at the integration tests, you find also how to use Mikel mail component for sending mails outside.

https://github.com/4commerce-technologies-AG/midi-smtp-server/blob/master/test/construct/base_integration_test_class.rb

More to find on Mikels page at https://github.com/mikel/mail

Hope that guide you

Tom

**Comment by TomFreudenberg** [comment]
Peter, I close this as it is not an issue.

Please feel free to continue asking.

Tom
