### ISSUE TITLE
Address not available?

### ISSUE THREAD

**Issue by echan00** [4commerce-technologies-AG/midi-smtp-server#7]
It looks like I'm getting an error saying the address is already in use after I try to start the server.

```
Errno::EADDRNOTAVAIL: Can't assign requested address - bind(2)
from /Users/erikchan/.rvm/gems/ruby-2.0.0-p353/gems/midi-smtp-server-2.1.2/lib/midi-smtp-server.rb:654:in `initialize'
```

I've tried changing both my port and address to other numbers but still no luck.

**Comment by echan00** [comment]
Seems to work now.. weirdly

**Comment by echan00** [comment]
This seems to work fine on rails console:

`TCPSocket.open('127.0.0.1', 2525) `

But I still get the error when starting the smtp server.

**Comment by TomFreudenberg** [comment]
Hi Eric ( @echan00 )

sorry for late response, be on vacation currently.

Could you please give a short code sample what you have done so that I can check this. I have created a number of services with that component without an issue to that behavior.

Thanks
Tom

**Comment by echan00** [comment]
Thanks @TomFreudenberg. It looks like the problem was that the address was really in use, I stopped having the problem after a machine restart.

Appreciate your support!
